### PR TITLE
Limit watchtower updates to storagenode container

### PR DESCRIPTION
**Pull request by ReneSmeekes**
Would require some verification if this works as intended. Both storagenode and watchtower run fine with these changes, but haven't confirmed updates work on storagenode container but not on others.

### CODE REVIEW

**Comment by ReneSmeekes** [comment]
I've verified with the v0.10.1 update that updating still works as expected.

**Comment by mcumings** [comment]
Thanks for this.  I was just about to look into doing the same when I noticed it was updating every container on my docker host.

**Comment by meetyg** [comment]
I think a simpler approach would be to just pass the container name to watchtower, as I mentioned in this issue: https://github.com/storj/docs/issues/53

**Comment by ReneSmeekes** [comment]
While for my personal use I prefer using labels, I agree that your suggestion is cleaner for Storj.

I prefer the label approach because that way when you want to add a container to monitor, you don't need to remove and restart the watchtower container to include the new container name. This likely won't apply to 99% of SNO's so the cleaner approach that keeps the run commands shorter is preferable. I changed this PR accordingly, included the changes in the ARM command and added a link to documentation in case users want to make their own changes.

**Comment by meetyg** [comment]
There is a suggestion to add watchtower itself to be updated also (does that by default if no specific container is specified).
See comment: https://github.com/storj/docs/issues/53#issuecomment-490214268

What do you think?

**Comment by ReneSmeekes** [comment]
added

**Pull request merged**
