### PR TITLE
Remove specific NAS references in favor of a more generic and compact doc

### PR DESCRIPTION
**Pull request by ReneSmeekes**
I've removed references to specific NAS brands. Recent PR #34 added instructions for QNAP while those instructions did not deviate from the base instructions and in the process made Synology instructions less convenient. Instead of adding copies of the instructions for every brand, I combined them and simply added a note to use sudo or add the user to the docker group if you run into permission errors.

I also added some other minor clarifications for the token. Moved the mention of the email address being part of the token to the place where you need it instead of in the earlier text where it may be skipped over.
Added small clarifications to bandwidth (per month) and to use CMD in windows, since it has prove to cause fewer issues than powershell.

@jensamberg  I realize this reverts some changes you made to include QNAP, but I think the initial confusion started by including specific Synology instructions to begin with. QNAP users should have always followed the same instructions as everyone else. Any comments are welcome though.

### CODE REVIEW

**Comment by jensamberg** [comment]
@ReneSmeekes In general you are correct. However you removed the sudo command for Synology.
I do not know where it come from. I do not know if it is really necessary to use sudo on Synology NAS

**Comment by jensamberg** [comment]
@ReneSmeekes Ah ok now I saw you test it on Synology without sudo

**Comment by ReneSmeekes** [comment]
Something must be off with the timestamps of messages. My previous message says it was posted "12 minutes from now". Which is interesting. I didn't know I had time traveling ability.

For identity creation and signing it works without. And for docker commands I generalized the note for anyone running into permission errors they should start with sudo or add their user to the docker group. That should catch the issue for Synology as well. Docker commands do needs sudo on synology.

**Comment by heunland** [comment]
Please do not make a PR now to the repo, we have to revert a change we made that negatively affected formatting before anything new is added.

**Comment by ReneSmeekes** [comment]
I noticed the formatting issues and already decided to wait until that's resolved. Aside from the formatting it did already look like a lot of the things this PR addressed have changed for the better. The specific Synology reference could be more generalized, since it'll likely apply to more systems. But I'll have to do some re-reading when the new instructions are back up. If still needed, I'll create a new PR then. For now I'll close this one to remove clutter.

**Comment by heunland** [comment]
We have reverted to prior version so the formatting issue is now fixed.

**Pull request closed without merging**
