### PR TITLE
code: Add Git conventions document

### PR DESCRIPTION
**Pull request by ifraixedes**
Add the first known convention that we apply to Storj git repositories.

I asked about Git conventions when I've joined, however I didn't get any about it, however recently, I was told of what I wrote in this new document.

There are probably more however I'm not aware of them, so the doc may be the trigger to add them once somebody realize about them.

### CODE REVIEW

**Comment by stefanbenten** [comment]
@ifraixedes Not sure if those additions are necessary or add much of a benefit.

**Comment by ifraixedes** [comment]
They are to me because I've never considered branches which are pushed to GitHub are sharable (in terms that anybody can push commits without previous agreement with the author) by default, while in Storj they are, so once they are pushed to GitHub we don't want that pushes are forced (for example because I preferred to use rebase rather than merge for updating WIP branches from master), so they are conventions which are good to know in advance.

**Comment by wthorp** [comment]
I guess all I'm saying is we could probably use a gentler hand.  I'd be surprised if 75% of Storj developers abide by what you're recommending here.  There are certainly best/better practices that can be followed (like use force-with-lease instead of force), but I would focus on _why_ things might be preferred and tips for making those recommendation more actionable (EG: create an alias, etc).

**Comment by ifraixedes** [comment]
> I think in general creating strict rules like this isn't typical at Storj. Its great to have strong opinions (loosely held) and educate others on the background of these opinions. Was there a particular experience you had that makes you think we need these ALL-CAPS rules?

I was not always updating my branch with rebase and I was told for not doing so.
These are not my preferences, totally the opposite to my ones.

> I guess all I'm saying is we could probably use a gentler hand. I'd be surprised if 75% of Storj developers abide by what you're recommending here.

I think that everybody abides it, I haven't seen any rebase since I've started.

> There are certainly best/better practices that can be followed (like use force-with-lease instead of force), but I would focus on why things might be preferred and tips for making those recommendation more actionable

I don't get this, it explains what exactly to do and why we do so as it was told to me, so I see that they are actionable.

**Comment by ifraixedes** [comment]
by the way, the PR comment mentions why I wrote this and the purpose of having it.

**Comment by thepaul** [comment]
There are cases when it would be reasonable to force-push a shared branch, but it should be understood that that can be messy and should be avoided. Can we just say "don't make it a part of your regular workflow"?

**Comment by navillasa** [comment]
> There are cases when it would be reasonable to force-push a shared branch, but it should be understood that that can be messy and should be avoided. Can we just say "don't make it a part of your regular workflow"?

I agree with this. I also think this PR adds helpful guidance to the repo, because I think it is a sort of unspoken (or only spoken when someone breaks it) rule not to force-push to branches, and it would be good to have it written somewhere "official."

**Comment by ifraixedes** [comment]
maybe the way of allowing to have a different workflow is using forks https://github.com/storj/storj/pull/2679#event-2526163421 :thinking:

**Comment by ifraixedes** [comment]
We moved to gerrit with a different workflow so this information isn't valid anymore.

**Pull request closed without merging**
