### PR TITLE
Added notes for QNAP NAS

### PR DESCRIPTION
**Pull request by jensamberg**
Added notes for QNAP NAS. I tested it on QNAP TVS463 and it runs perfect.

### CODE REVIEW

**Comment by stefanbenten** [comment]
Hello @jensamberg!
Nice that you like to add the steps for the QNAP. As they are the same as for the above Synology one, please just add QNAP to the previous Synology Instructions, instead of making the instructions unnecessary longer. Thanks!

**Comment by jensamberg** [comment]
Hello @stefanbenten .

> As they are the same as for the above Synology one, please just add QNAP to the previous Synology

It is not exactly the same. On QNAP it is not necessary to use sudo. I highly recommend to do it without sudo on QNAP. This is the reason I create the PR with QNAP without sudo.

But maybe on Synology sudo is also not mandatory and it is the same.

**Comment by stefanbenten** [comment]
Then please add a note above the run command that outlines that 👍 
I would like to hold off on adding a specific run command for every NAS brand we have.

Something like:
`// on Synology run this command with sudo`

Thank you for the contribution!

**Comment by jensamberg** [comment]
Ok added note for Synology and removed sudo.

**Comment by ifraixedes** [comment]
It looks good to me,  @stefanbenten any other objection?

**Pull request merged**
