### PR TITLE
Add documentation for registering a private endpoint on a satellite

### PR DESCRIPTION
**Pull request by aleitner**

### CODE REVIEW

**Comment by ifraixedes** [comment]
The content looks good to me although I haven't tried to follow, probably @VinozzZ is better to asses it than me.

Regarding the format I would prefer to have each code snipped below the text and the last 3 point to be aligned with the other 2 Example: https://gist.github.com/ifraixedes/a8ffdf500df6c9679038c207399a2673

**Comment by VinozzZ** [comment]
I like the example @ifraixedes provided in his gist! Other than that, it looks great

**Comment by egonelbre** [comment]
Any reason https://github.com/storj/docs/blob/master/code/Endpoint.md#adding-a-new-endpoint wasn't sufficient?

**Comment by VinozzZ** [comment]
@egonelbre I was thinking this one is specific for a private endpoint which the existing documentation is not mentioning about the different types of endpoints

**Comment by egonelbre** [comment]
The question was partly, whether we can improve the existing document to capture the private vs public nature of registering things.

**Comment by ifraixedes** [comment]
@aleitner can you reply @egonelbre?

**Pull request closed without merging**
