### PR TITLE
initial docs on static port allocations for edge services

### PR DESCRIPTION
**Pull request by nergdron**
wording could use improvement, assignment of the top of the allocation block to the debug port is arbitrary. feedback much appreciated!

### CODE REVIEW

**Comment by Erikvv** [comment]
I think the introduction needs some more context.

Reading this I now expect the linkshare service to be available at https://link.us1.storjshare.io:13201/ yet this is not the case.

**Comment by nergdron** [comment]
initial testing against both `htz-nonprod-linksharing-prometheus-0` and `htz-prod-ops-prometheus-0` were successful, will expand testing into most of non-prod once I have edge services sorted out.

**Comment by wthorp** [comment]
This is tricky.  I previously thought we'd change the production defaults for the Edge Services to reflect these values.  Yet I wonder if a 3rd party would deploy multiple edge services to the same machine.  If not, these ports are "unreasonable" production defaults, because values like 80 and 443 are reasonable.  Perhaps its safe to call these service values "internal to Storj", and in that sense, maybe we're just documenting this in the wrong place?

**Comment by nergdron** [comment]
we're gonna shelve this, pending more discussion internally.

**Pull request closed without merging**
